#!/bin/python3
"""
Author  :   Gaël Mariot
Date    :   20.02.2020
Name    :   const.py
Desc.   :   This file contains contants for the project
"""

HEADER_LENGTH = 14
START_HEADER = 0
END_HEADER = HEADER_LENGTH

SIGNATURE_SIZE = 2
FILE_SIZE_SIZE = 4
RESERVED_SIZE = 4
DATA_OFFSET_SIZE = 4


INFO_HEADER_LENGTH = 40
START_INFO_HEADER = END_HEADER
END_INFO_HEADER = INFO_HEADER_LENGTH+HEADER_LENGTH

SIZE = 4
WIDTH = 4
HEIGHT = 4
PLANES = 2
BITS_PER_PIXEL = 2
COMPRESSION = 4
IMAGE_SIZE = 4
X_PIXEL_PER_M = 4
Y_PIXEL_PER_M = 4
COLORS_USED = 4
IMPORTANT_COLORS = 4
